### PR TITLE
Added mistakes and random wait times

### PR DESCRIPTION
**Pull request by the-moisrex**
Added:

- Mistakes which gets fixed
- Random wait times
- Additional random time when it reaches white spaces

Check if anything is wrong with the code, it worked on the first tries :)

### CODE REVIEW

**Comment by the-moisrex** [comment]
video-2020-09-15_19 42 04

**Comment by lunasorcery** [comment]
Do you make a habit of completely rewriting other people's projects?

**Comment by the-moisrex** [comment]
Sorry I was bored :)

**Comment by the-moisrex** [comment]
You really are not gonna merge it? why?

**Comment by lunasorcery** [comment]
It's rather like walking up to a comedian after a set and telling them how to improve their joke. You've sent a PR for a feature I haven't asked for, that almost completely rewrites the tool, and act surprised when I don't want to take it?

By mutating the output stream, your change is liable to break behavior when the tool is placed in the middle of a pipeline. Additionally, I think your code will cause issues if it starts typing mistakes in the middle of a multi-byte input character.

You're welcome to your own version of the tool, but I won't merge the change, because it would mean the repo on my profile is no longer the joke I wanted to tell.

**Comment by the-moisrex** [comment]
Those technical issues are resolvable. But I'll make sure not to bother your twitter jokes with my pull requests anymore.

**Pull request closed without merging**
